<?php

/**
 * @file
 * Contains event_database_push.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function event_database_push_help(string $route_name): ?string {
  switch ($route_name) {
    // Main module help for the event_database_push module.
    case 'help.page.event_database_push':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Push events to Event API') . '</p>';

      return $output;

    default:
  }
}

/**
 * Implements hook_node_insert().
 */
function event_database_push_node_insert(NodeInterface $node): void {
  $handler = \Drupal::service('event_database_push.handler');
  $handler->handle($node, 'insert');
}

/**
 * Implements hook_node_update().
 */
function event_database_push_node_update(NodeInterface $node): void {
  $handler = \Drupal::service('event_database_push.handler');
  $handler->handle($node, 'update');
}

/**
 * Implements hook_node_delete().
 */
function event_database_push_node_delete(NodeInterface $node): void {
  $handler = \Drupal::service('event_database_push.handler');
  $handler->handle($node, 'delete');
}
